table DadosContabeis
	lineageTag: 9002250e-29ff-41e2-9d64-fe0d80b3b7f0

	column ID_Conta
		dataType: int64
		formatString: 0
		lineageTag: 1b4286a2-e617-45f3-9299-602b6cc5c1b9
		summarizeBy: none
		sourceColumn: ID_Conta

		annotation SummarizationSetBy = Automatic

	column Ano_2019
		dataType: int64
		formatString: 0
		lineageTag: 7be80ff6-7b83-45f4-b97f-0378199afb12
		summarizeBy: sum
		sourceColumn: Ano_2019

		annotation SummarizationSetBy = Automatic

	column Ano_2020
		dataType: double
		lineageTag: bd97dd3d-6fe3-4eb4-bf15-93a0bbaedcd2
		summarizeBy: sum
		sourceColumn: Ano_2020

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ano_2021
		dataType: double
		lineageTag: befc5845-cd26-4aab-b3d8-b4b0fe847992
		summarizeBy: sum
		sourceColumn: Ano_2021

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ano_2022
		dataType: double
		lineageTag: 08fe36b5-30d2-435a-bb08-415e77ffa236
		summarizeBy: sum
		sourceColumn: Ano_2022

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ano_2023
		dataType: double
		lineageTag: 8e6eda23-0208-42a9-a5a8-227c5a66e5e3
		summarizeBy: sum
		sourceColumn: Ano_2023

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DadosContabeis = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\LEAO\OneDrive\Documentos\DSA - Data Science Academy\Cap09\Dataset\Dataset.xlsx"), null, true),
				    DadosContabeis_Sheet = Fonte{[Item="DadosContabeis",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(DadosContabeis_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID_Conta", Int64.Type}, {"Ano_2019", Int64.Type}, {"Ano_2020", type number}, {"Ano_2021", type number}, {"Ano_2022", type number}, {"Ano_2023", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

